-- 1. Create Checklists Table
create table if not exists public.checklists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null,
  created_at timestamptz default now(),
  data jsonb,
  synced boolean default true,
  pdf_url text,
  email_sent boolean default false,
  archived boolean default false,
  archived_at timestamptz
);

-- 2. Enable Row Level Security (RLS)
alter table public.checklists enable row level security;

-- 3. RLS Policies for Checklists
create policy "Users can view their own checklists" on public.checklists
  for select using (auth.uid() = user_id);

create policy "Users can insert their own checklists" on public.checklists
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own checklists" on public.checklists
  for update using (auth.uid() = user_id);

create policy "Users can delete their own checklists" on public.checklists
  for delete using (auth.uid() = user_id);

-- 4. Storage Bucket Setup
-- We insert the bucket configuration directly. 
-- NOTE: If this fails, please create a public bucket named 'mpx-reports' in the Storage UI.
insert into storage.buckets (id, name, public) 
values ('mpx-reports', 'mpx-reports', true)
on conflict (id) do nothing;

-- 5. Storage Policies (Bucket: mpx-reports)
-- Allow authenticated users to upload files to the bucket
create policy "Authenticated Users Upload" on storage.objects
  for insert with check ( bucket_id = 'mpx-reports' and auth.role() = 'authenticated' );

-- Allow anyone to view files (since it's a public bucket, we need to allow public read access)
create policy "Public Read Access" on storage.objects
  for select using ( bucket_id = 'mpx-reports' );
